# Churn Prediction using ANN in Pytorch

## 1. Importing Libraries

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

## 2. Loading Dataset

In [46]:
url = "https://media.githubusercontent.com/media/fatahrahimi330/100-Machine-Learning-Projects/refs/heads/master/69-Churn%20Prediction%20ANN%20Pytorch/Churn_Modelling.csv"

In [47]:
df = pd.read_csv(url)
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

## 3. Data Preprocessing

In [48]:
df.shape

(10000, 14)

In [49]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
RowNumber,10000.0,5.000500e+03,2886.895680,1.00,2500.75,5.000500e+03,7.500250e+03,10000.00
CustomerId,10000.0,1.569094e+07,71936.186123,15565701.00,15628528.25,1.569074e+07,1.575323e+07,15815690.00
CreditScore,10000.0,6.505288e+02,96.653299,350.00,584.00,6.520000e+02,7.180000e+02,850.00
Age,10000.0,3.892180e+01,10.487806,18.00,32.00,3.700000e+01,4.400000e+01,92.00
Tenure,10000.0,5.012800e+00,2.892174,0.00,3.00,5.000000e+00,7.000000e+00,10.00
Balance,10000.0,7.648589e+04,62397.405202,0.00,0.00,9.719854e+04,1.276442e+05,250898.09
NumOfProducts,10000.0,1.530200e+00,0.581654,1.00,1.00,1.000000e+00,2.000000e+00,4.00
HasCrCard,10000.0,7.055000e-01,0.455840,0.00,0.00,1.000000e+00,1.000000e+00,1.00
IsActiveMember,10000.0,5.151000e-01,0.499797,0.00,0.00,1.000000e+00,1.000000e+00,1.00
EstimatedSalary,10000.0,1.000902e+05,57510.492818,11.58,51002.11,1.001939e+05,1.493882e+05,199992.48
Exited,10000.0,2.037000e-01,0.402769,0.00,0.00,0.000000e+00,0.000000e+00,1.00

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [51]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [52]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [53]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [54]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:,2])

In [55]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

transformers = [('encoder', OneHotEncoder(), [1])]
ct = ColumnTransformer(transformers = transformers, remainder = "passthrough")
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [57]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [58]:
import torch
from torch.utils.data import DataLoader, TensorDataset
# 1. Convert to tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)  # shape (N, 1)

# 2. DataLoader
train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=32, shuffle=True)

In [59]:
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)  # shape (N, 1)

# 2. DataLoader
test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=32, shuffle=False)

## 4. Build the Model

In [60]:
import torch
import torch.nn as nn

In [61]:
class ANN(nn.Module):
    def __init__(self, in_features):
        super(ANN, self).__init__()
        self.fc1 = nn.Linear(in_features ,6)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(6, 6)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(6, 1)
        self.sigmoid = nn.Sigmoid()


    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        x = self.sigmoid(x)
        return x

In [62]:
X_train.shape

torch.Size([8000, 12])

In [63]:
model = ANN(in_features=12)

In [64]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [65]:
from torchinfo import summary
summary(model)

=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
ANN                                      --
├─Linear: 1-1                            78
├─ReLU: 1-2                              --
├─Linear: 1-3                            42
├─ReLU: 1-4                              --
├─Linear: 1-5                            7
├─Sigmoid: 1-6                           --
=================================================================
Total params: 127
Trainable params: 127
Non-trainable params: 0
=================================================================

In [66]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

## 5. Loop and Fit the Model

In [69]:
epochs = 100
# 4. Training Loop
for epoch in range(epochs):
    model.train()
    total_loss    = 0
    total_correct = 0
    total_samples = 0

    for X_batch, y_batch in tqdm(train_loader):
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss    = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()

        # accuracy
        predicted = (outputs >= 0.5).float()          # threshold at 0.5
        total_correct += (predicted == y_batch).sum().item()
        total_samples += y_batch.size(0)
        total_loss    += loss.item()

    avg_loss = total_loss / len(train_loader)
    accuracy = total_correct / total_samples * 100


    print(f"Epoch {epoch+1:3d}/100 | Loss: {avg_loss:.4f} | Accuracy: {accuracy:.2f}%")

100%|██████████| 250/250 [00:00<00:00, 638.64it/s]

Epoch   1/100 | Loss: 0.3337 | Accuracy: 86.10%

100%|██████████| 250/250 [00:00<00:00, 728.72it/s]

Epoch   2/100 | Loss: 0.3336 | Accuracy: 86.21%

100%|██████████| 250/250 [00:00<00:00, 737.31it/s]

Epoch   3/100 | Loss: 0.3331 | Accuracy: 86.34%

100%|██████████| 250/250 [00:00<00:00, 768.77it/s]

Epoch   4/100 | Loss: 0.3333 | Accuracy: 86.24%

100%|██████████| 250/250 [00:00<00:00, 721.78it/s]

Epoch   5/100 | Loss: 0.3332 | Accuracy: 86.29%

100%|██████████| 250/250 [00:00<00:00, 681.09it/s]

Epoch   6/100 | Loss: 0.3335 | Accuracy: 86.28%

100%|██████████| 250/250 [00:00<00:00, 734.81it/s]

Epoch   7/100 | Loss: 0.3341 | Accuracy: 86.24%

100%|██████████| 250/250 [00:00<00:00, 716.96it/s]

Epoch   8/100 | Loss: 0.3334 | Accuracy: 86.33%

100%|██████████| 250/250 [00:00<00:00, 740.83it/s]

Epoch   9/100 | Loss: 0.3342 | Accuracy: 86.22%

100%|██████████| 250/250 [00:00<00:00, 782.11it/s]

Epoch  10/100 | Loss: 0.3338 | Accuracy: 86.29%

100%|██████████| 250/250 [00:00<00:00, 723.38it/s]

Epoch  11/100 | Loss: 0.3332 | Accuracy: 86.22%

100%|██████████| 250/250 [00:00<00:00, 776.08it/s]

Epoch  12/100 | Loss: 0.3333 | Accuracy: 86.25%

100%|██████████| 250/250 [00:00<00:00, 781.51it/s]

Epoch  13/100 | Loss: 0.3329 | Accuracy: 86.17%

100%|██████████| 250/250 [00:00<00:00, 654.95it/s]

Epoch  14/100 | Loss: 0.3335 | Accuracy: 86.21%

100%|██████████| 250/250 [00:00<00:00, 766.56it/s]

Epoch  15/100 | Loss: 0.3335 | Accuracy: 86.26%

100%|██████████| 250/250 [00:00<00:00, 765.01it/s]

Epoch  16/100 | Loss: 0.3328 | Accuracy: 86.10%

100%|██████████| 250/250 [00:00<00:00, 740.91it/s]

Epoch  17/100 | Loss: 0.3332 | Accuracy: 86.20%

100%|██████████| 250/250 [00:00<00:00, 771.07it/s]

Epoch  18/100 | Loss: 0.3336 | Accuracy: 86.24%

100%|██████████| 250/250 [00:00<00:00, 766.62it/s]

Epoch  19/100 | Loss: 0.3338 | Accuracy: 86.41%

100%|██████████| 250/250 [00:00<00:00, 725.27it/s]

Epoch  20/100 | Loss: 0.3334 | Accuracy: 86.33%

100%|██████████| 250/250 [00:00<00:00, 774.23it/s]

Epoch  21/100 | Loss: 0.3331 | Accuracy: 86.25%

100%|██████████| 250/250 [00:00<00:00, 751.95it/s]

Epoch  22/100 | Loss: 0.3338 | Accuracy: 86.21%

100%|██████████| 250/250 [00:00<00:00, 727.21it/s]

Epoch  23/100 | Loss: 0.3330 | Accuracy: 86.40%

100%|██████████| 250/250 [00:00<00:00, 738.85it/s]

Epoch  24/100 | Loss: 0.3332 | Accuracy: 86.44%

100%|██████████| 250/250 [00:00<00:00, 702.97it/s]

Epoch  25/100 | Loss: 0.3329 | Accuracy: 86.24%

100%|██████████| 250/250 [00:00<00:00, 495.89it/s]

Epoch  26/100 | Loss: 0.3332 | Accuracy: 86.26%

100%|██████████| 250/250 [00:00<00:00, 561.25it/s]

Epoch  27/100 | Loss: 0.3328 | Accuracy: 86.16%

100%|██████████| 250/250 [00:00<00:00, 521.14it/s]

Epoch  28/100 | Loss: 0.3334 | Accuracy: 86.15%

100%|██████████| 250/250 [00:00<00:00, 552.26it/s]

Epoch  29/100 | Loss: 0.3333 | Accuracy: 86.15%

100%|██████████| 250/250 [00:00<00:00, 489.00it/s]

Epoch  30/100 | Loss: 0.3329 | Accuracy: 86.26%

100%|██████████| 250/250 [00:00<00:00, 678.28it/s]

Epoch  31/100 | Loss: 0.3334 | Accuracy: 86.38%

100%|██████████| 250/250 [00:00<00:00, 757.07it/s]

Epoch  32/100 | Loss: 0.3335 | Accuracy: 86.49%

100%|██████████| 250/250 [00:00<00:00, 745.09it/s]

Epoch  33/100 | Loss: 0.3332 | Accuracy: 86.20%

100%|██████████| 250/250 [00:00<00:00, 731.73it/s]

Epoch  34/100 | Loss: 0.3335 | Accuracy: 86.16%

100%|██████████| 250/250 [00:00<00:00, 708.42it/s]

Epoch  35/100 | Loss: 0.3330 | Accuracy: 86.14%

100%|██████████| 250/250 [00:00<00:00, 754.24it/s]

Epoch  36/100 | Loss: 0.3329 | Accuracy: 86.26%

100%|██████████| 250/250 [00:00<00:00, 715.72it/s]

Epoch  37/100 | Loss: 0.3330 | Accuracy: 86.16%

100%|██████████| 250/250 [00:00<00:00, 744.44it/s]

Epoch  38/100 | Loss: 0.3333 | Accuracy: 86.14%

100%|██████████| 250/250 [00:00<00:00, 691.22it/s]

Epoch  39/100 | Loss: 0.3334 | Accuracy: 86.28%

100%|██████████| 250/250 [00:00<00:00, 737.00it/s]

Epoch  40/100 | Loss: 0.3332 | Accuracy: 86.30%

100%|██████████| 250/250 [00:00<00:00, 693.10it/s]

Epoch  41/100 | Loss: 0.3334 | Accuracy: 86.21%

100%|██████████| 250/250 [00:00<00:00, 708.34it/s]

Epoch  42/100 | Loss: 0.3332 | Accuracy: 86.06%

100%|██████████| 250/250 [00:00<00:00, 761.57it/s]

Epoch  43/100 | Loss: 0.3326 | Accuracy: 86.12%

100%|██████████| 250/250 [00:00<00:00, 702.76it/s]

Epoch  44/100 | Loss: 0.3333 | Accuracy: 86.20%

100%|██████████| 250/250 [00:00<00:00, 723.65it/s]

Epoch  45/100 | Loss: 0.3335 | Accuracy: 86.10%

100%|██████████| 250/250 [00:00<00:00, 764.53it/s]

Epoch  46/100 | Loss: 0.3332 | Accuracy: 86.21%

100%|██████████| 250/250 [00:00<00:00, 759.66it/s]

Epoch  47/100 | Loss: 0.3331 | Accuracy: 86.17%

100%|██████████| 250/250 [00:00<00:00, 755.81it/s]

Epoch  48/100 | Loss: 0.3332 | Accuracy: 86.31%

100%|██████████| 250/250 [00:00<00:00, 771.00it/s]

Epoch  49/100 | Loss: 0.3328 | Accuracy: 86.36%

100%|██████████| 250/250 [00:00<00:00, 739.58it/s]

Epoch  50/100 | Loss: 0.3333 | Accuracy: 86.10%

100%|██████████| 250/250 [00:00<00:00, 774.03it/s]

Epoch  51/100 | Loss: 0.3332 | Accuracy: 86.31%

100%|██████████| 250/250 [00:00<00:00, 741.84it/s]

Epoch  52/100 | Loss: 0.3332 | Accuracy: 86.22%

100%|██████████| 250/250 [00:00<00:00, 771.77it/s]

Epoch  53/100 | Loss: 0.3332 | Accuracy: 86.34%

100%|██████████| 250/250 [00:00<00:00, 774.39it/s]

Epoch  54/100 | Loss: 0.3330 | Accuracy: 86.24%

100%|██████████| 250/250 [00:00<00:00, 749.47it/s]

Epoch  55/100 | Loss: 0.3331 | Accuracy: 86.19%

100%|██████████| 250/250 [00:00<00:00, 738.62it/s]

Epoch  56/100 | Loss: 0.3328 | Accuracy: 86.11%

100%|██████████| 250/250 [00:00<00:00, 763.64it/s]

Epoch  57/100 | Loss: 0.3333 | Accuracy: 86.29%

100%|██████████| 250/250 [00:00<00:00, 582.48it/s]

Epoch  58/100 | Loss: 0.3329 | Accuracy: 86.11%

100%|██████████| 250/250 [00:00<00:00, 729.95it/s]

Epoch  59/100 | Loss: 0.3332 | Accuracy: 86.25%

100%|██████████| 250/250 [00:00<00:00, 559.83it/s]

Epoch  60/100 | Loss: 0.3330 | Accuracy: 86.19%

100%|██████████| 250/250 [00:00<00:00, 507.66it/s]

Epoch  61/100 | Loss: 0.3335 | Accuracy: 86.11%

100%|██████████| 250/250 [00:00<00:00, 569.18it/s]

Epoch  62/100 | Loss: 0.3330 | Accuracy: 86.22%

100%|██████████| 250/250 [00:00<00:00, 462.10it/s]

Epoch  63/100 | Loss: 0.3326 | Accuracy: 86.50%

100%|██████████| 250/250 [00:00<00:00, 498.31it/s]

Epoch  64/100 | Loss: 0.3325 | Accuracy: 86.42%

100%|██████████| 250/250 [00:00<00:00, 557.60it/s]

Epoch  65/100 | Loss: 0.3321 | Accuracy: 86.36%

100%|██████████| 250/250 [00:00<00:00, 781.66it/s]

Epoch  66/100 | Loss: 0.3322 | Accuracy: 86.22%

100%|██████████| 250/250 [00:00<00:00, 777.24it/s]

Epoch  67/100 | Loss: 0.3322 | Accuracy: 86.17%

100%|██████████| 250/250 [00:00<00:00, 678.11it/s]

Epoch  68/100 | Loss: 0.3318 | Accuracy: 86.22%

100%|██████████| 250/250 [00:00<00:00, 786.56it/s]

Epoch  69/100 | Loss: 0.3325 | Accuracy: 86.17%

100%|██████████| 250/250 [00:00<00:00, 767.10it/s]

Epoch  70/100 | Loss: 0.3322 | Accuracy: 86.21%

100%|██████████| 250/250 [00:00<00:00, 711.14it/s]

Epoch  71/100 | Loss: 0.3318 | Accuracy: 86.19%

100%|██████████| 250/250 [00:00<00:00, 765.05it/s]

Epoch  72/100 | Loss: 0.3321 | Accuracy: 86.25%

100%|██████████| 250/250 [00:00<00:00, 787.06it/s]

Epoch  73/100 | Loss: 0.3318 | Accuracy: 86.29%

100%|██████████| 250/250 [00:00<00:00, 745.00it/s]

Epoch  74/100 | Loss: 0.3321 | Accuracy: 86.33%

100%|██████████| 250/250 [00:00<00:00, 783.77it/s]

Epoch  75/100 | Loss: 0.3319 | Accuracy: 86.36%

100%|██████████| 250/250 [00:00<00:00, 776.81it/s]

Epoch  76/100 | Loss: 0.3317 | Accuracy: 86.17%

100%|██████████| 250/250 [00:00<00:00, 705.13it/s]

Epoch  77/100 | Loss: 0.3316 | Accuracy: 86.25%

100%|██████████| 250/250 [00:00<00:00, 768.75it/s]

Epoch  78/100 | Loss: 0.3318 | Accuracy: 86.34%

100%|██████████| 250/250 [00:00<00:00, 737.61it/s]

Epoch  79/100 | Loss: 0.3317 | Accuracy: 86.05%

100%|██████████| 250/250 [00:00<00:00, 731.71it/s]

Epoch  80/100 | Loss: 0.3317 | Accuracy: 86.35%

100%|██████████| 250/250 [00:00<00:00, 769.45it/s]

Epoch  81/100 | Loss: 0.3315 | Accuracy: 86.21%

100%|██████████| 250/250 [00:00<00:00, 777.66it/s]

Epoch  82/100 | Loss: 0.3319 | Accuracy: 86.26%

100%|██████████| 250/250 [00:00<00:00, 742.03it/s]

Epoch  83/100 | Loss: 0.3315 | Accuracy: 86.22%

100%|██████████| 250/250 [00:00<00:00, 784.28it/s]

Epoch  84/100 | Loss: 0.3316 | Accuracy: 86.04%

100%|██████████| 250/250 [00:00<00:00, 775.61it/s]

Epoch  85/100 | Loss: 0.3314 | Accuracy: 86.29%

100%|██████████| 250/250 [00:00<00:00, 745.67it/s]

Epoch  86/100 | Loss: 0.3312 | Accuracy: 86.24%

100%|██████████| 250/250 [00:00<00:00, 747.38it/s]

Epoch  87/100 | Loss: 0.3316 | Accuracy: 86.21%

100%|██████████| 250/250 [00:00<00:00, 772.03it/s]

Epoch  88/100 | Loss: 0.3316 | Accuracy: 86.28%

100%|██████████| 250/250 [00:00<00:00, 736.13it/s]

Epoch  89/100 | Loss: 0.3313 | Accuracy: 86.24%

100%|██████████| 250/250 [00:00<00:00, 785.18it/s]

Epoch  90/100 | Loss: 0.3315 | Accuracy: 86.19%

100%|██████████| 250/250 [00:00<00:00, 744.42it/s]

Epoch  91/100 | Loss: 0.3310 | Accuracy: 86.26%

100%|██████████| 250/250 [00:00<00:00, 699.85it/s]

Epoch  92/100 | Loss: 0.3312 | Accuracy: 86.16%

100%|██████████| 250/250 [00:00<00:00, 784.41it/s]

Epoch  93/100 | Loss: 0.3309 | Accuracy: 86.33%

100%|██████████| 250/250 [00:00<00:00, 753.84it/s]

Epoch  94/100 | Loss: 0.3308 | Accuracy: 86.24%

100%|██████████| 250/250 [00:00<00:00, 559.07it/s]

Epoch  95/100 | Loss: 0.3317 | Accuracy: 86.30%

100%|██████████| 250/250 [00:00<00:00, 545.35it/s]

Epoch  96/100 | Loss: 0.3315 | Accuracy: 86.16%

100%|██████████| 250/250 [00:00<00:00, 533.48it/s]

Epoch  97/100 | Loss: 0.3310 | Accuracy: 86.20%

100%|██████████| 250/250 [00:00<00:00, 513.62it/s]

Epoch  98/100 | Loss: 0.3314 | Accuracy: 86.20%

100%|██████████| 250/250 [00:00<00:00, 477.99it/s]

Epoch  99/100 | Loss: 0.3308 | Accuracy: 86.28%

100%|██████████| 250/250 [00:00<00:00, 483.27it/s]

Epoch 100/100 | Loss: 0.3312 | Accuracy: 86.11%

## 6. Make Prediction

In [71]:
# 1. Scale the input (same scaler from training)
sample = sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])

# 2. Convert to tensor
sample_tensor = torch.tensor(sample, dtype=torch.float32)

# 3. Predict
model.eval()
with torch.no_grad():
    output = model(sample_tensor)
    result = (output >= 0.5)

print(result.item())  # True or False

False

## 7. Evaluate the Model

In [73]:
all_preds  = []
all_labels = []

# 1. Loop through test loader
model.eval()
with torch.no_grad():
    for X_batch, y_batch in test_loader:
        outputs   = model(X_batch)
        predicted = (outputs >= 0.5).float()

        all_preds.append(predicted)
        all_labels.append(y_batch)

# 2. Concatenate all batches
all_preds  = torch.cat(all_preds).numpy()
all_labels = torch.cat(all_labels).numpy()

In [74]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

accuracy = accuracy_score(all_labels, all_preds) * 100
cm       = confusion_matrix(all_labels, all_preds)
report   = classification_report(all_labels, all_preds)

print(f"Test Accuracy:  {accuracy:.2f}%")
print(f"Confusion Matrix:\n{cm}")
print(f"Classification Report:\n{report}")

Test Accuracy:  86.25%
Confusion Matrix:
[[1536   71]
 [ 204  189]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.88      0.96      0.92      1607
         1.0       0.73      0.48      0.58       393

    accuracy                           0.86      2000
   macro avg       0.80      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000